### ISSUE TITLE
Destaque en home de noticias 

### ISSUE THREAD

**Issue by RobertoRedGealc** [Asimovers/redgealc#176]
Cuando creo la noticia, tengo la opción de cliquear o no en el casillero "Destacado". Teóricamente, si no lo cliqueo, va a la página del país, y si cliqueo, va a la home. Ahora, lo haga o no lo haga, va siempre a la home.

**Comment by andres-avalancha** [comment]
Se ha realizado la correccion.
Ahora para que la noticia aparezca como destada en el home se debe hacer click en el la casilla "destacado"

Adjunto capturas:

![2020-04-09_031343](https://user-images.githubusercontent.com/31632227/78868043-2c542980-7a10-11ea-885d-96143433c2fd.jpg)

**Comment by RobertoRedGealc** [comment]
Ok

**Comment by RobertoRedGealc** [comment]
Ok, hecho. Gracias.
