### ISSUE TITLE
Texto principal de la línea de trabajo Coronavirus

### ISSUE THREAD

**Issue by RobertoRedGealc** [Asimovers/redgealc#177]
Ya sea que lo trabaje en Visual o en html, no me reconoce los saltos de página, ni los enlaces que coloco.

[Ver ejemplo](http://www2.redgealc.org/lineas-de-trabajo/coronavirus/)

**Comment by andres-avalancha** [comment]
Se ha realizado el ajuste solicitado.
URL: http://www2.redgealc.org/lineas-de-trabajo/coronavirus/

Captura: 
![2020-04-08_000211](https://user-images.githubusercontent.com/31632227/78743321-4b798b00-792c-11ea-915a-08cb2595da4a.jpg)

**Comment by RobertoRedGealc** [comment]
Ok, hecho
