### ISSUE TITLE
quitar de la home page bloque Newsletter

### ISSUE THREAD

**Issue by RobertoRedGealc** [Asimovers/redgealc#179]
Que por el momento no se vea. Luego quizás lo volvamos a habilitar.

**Comment by andres-avalancha** [comment]
Se ha realizado el ajuste.

![2020-04-07_041013](https://user-images.githubusercontent.com/31632227/78645545-b0c67100-7885-11ea-9933-d2ee28536f83.jpg)

**Comment by RobertoRedGealc** [comment]
Gracias.

**Comment by RobertoRedGealc** [comment]
Ok, hecho. Gracias.
