### ISSUE TITLE
También quitar de la home page bloque Servicios y herramientas

### ISSUE THREAD

**Issue by RobertoRedGealc** [Asimovers/redgealc#180]
Pero dejarlo en el menú superior, sólo quitar el bloque que está debajo de noticias.

**Comment by andres-avalancha** [comment]
Se ha realizado el ajuste.
![2020-04-07_040923](https://user-images.githubusercontent.com/31632227/78645477-9391a280-7885-11ea-8ccd-39124ce64d93.jpg)

**Comment by RobertoRedGealc** [comment]
Gracias

**Comment by RobertoRedGealc** [comment]
Ok, hecho. Gracias.
