### ISSUE TITLE
En el menú superior quitar catálogo de iniciativas

### ISSUE THREAD

**Issue by RobertoRedGealc** [Asimovers/redgealc#181]
![catalogo](https://user-images.githubusercontent.com/62720348/77689364-4c9bd700-6f80-11ea-8824-03f9475716fb.png)

**Comment by andres-avalancha** [comment]
Se ha realizado el ajuste.

![2020-04-07_040810](https://user-images.githubusercontent.com/31632227/78645371-71982000-7885-11ea-9aa4-fba7919dfa50.jpg)

**Comment by RobertoRedGealc** [comment]
Gracias

**Comment by RobertoRedGealc** [comment]
Ok, hecho. Gracias.
