### ISSUE TITLE
Cambiar color del botón Coronavirus en líneas de trabajo. 

### ISSUE THREAD

**Issue by RobertoRedGealc** [Asimovers/redgealc#183]
Ponerlo en verde.
![boton coronavirus](https://user-images.githubusercontent.com/62720348/77689869-2f1b3d00-6f81-11ea-889b-6757d26f08ae.png)

**Comment by andres-avalancha** [comment]
Se ha realizado el ajuste.
![2020-04-07_040033](https://user-images.githubusercontent.com/31632227/78644763-64c6fc80-7884-11ea-916e-6a784067cca1.jpg)

**Comment by RobertoRedGealc** [comment]
Sólo se ve en el microsoft explorer, no se ve en Chrome. Debería verse en todos los navegadores.

**Comment by andres-avalancha** [comment]
Estimado, una consulta, ¿probo borrar el cache del navegador?

Le adjunto dos capturas realizadas una desde chrome y de mobile evidenciando el color del boton.
Ante cualquier consulta o novedad me comenta, muchas gracias.

![Screenshot_20200407-232240](https://user-images.githubusercontent.com/31632227/78741375-2afb0200-7927-11ea-8007-de52a8dee642.png)
![2020-04-07_232214](https://user-images.githubusercontent.com/31632227/78741379-2c2c2f00-7927-11ea-88f2-e97963bde5d9.jpg)

**Comment by RobertoRedGealc** [comment]
Ok, hecho. Gracias.
